### ISSUE TITLE
Don't I have a board seat

### ISSUE THREAD

**Issue by sr5434** [intrepidmaths/.github#1]
don't I have a board seat

**Comment by intrepidbird** [comment]
No

**Comment by sr5434** [comment]
Then please remove me from the organization; if I don’t play a role then I don’t really have a reason to be here

**Comment by intrepidbird** [comment]
Ok. Please note that Board Seats are based on contributions. You still play a role without being a leader.

IntrepidBird and MalstromNitro are founders, while FoxJava and others have vast accomplishments/contributions.

The last time I checked you didn't do anything and you aren't one of the most skilled programmers/mathematicians either.
